name: CI

on:
  pull_request:
  push:
    branches: [development]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Docker Compose Action
        uses: isbang/compose-action@v1.5.1
        with:
          up-flags: "--build"
      - name: Install Postman CLI
        run: |
          curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh
      - name: Login to Postman CLI
        run: postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}
      - name: Run API tests
        run: |
          B_CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' art-gallery-api-services)
          echo "Backend IP addy is: $B_CONTAINER_IP"
          F_CONTAINER_IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' art-gallery-web-service)
          echo "Frontend IP addy is: $F_CONTAINER_IP"
          docker network ls
          postman collection run "22125528-61345646-96f3-4686-969b-2af89f43c52a" -e "22125528-a569d526-ef29-4672-93d2-e63cb678b112" --env-var "containerIP=$F_CONTAINER_IP"
          postman api lint 6f35e490-3148-419f-9233-582ec046e080
      - name: Linelint
        uses: fernandrone/linelint@master
      - name: Set up Node
        uses: actions/setup-node@v1
        with:
          node-version: 16.14.2
      - name: Install dependencies
        run: npm install
      - name: Prettier
        run: npm run format:check
      - name: Vale
        run: |
          sudo apt update
          sudo apt install snapd
          sudo snap install vale --edge
          npm run prose:check
